### ISSUE TITLE
Websocket implementation fails for web.whatsapp.com

### ISSUE THREAD

**Issue by Hesham-Elbadawi** [TechnikEmpire/CitadelCore.Windows#1]
Trying to connect to https://web.whatsapp.com.:

Request Headers:
Host: w6.web.whatsapp.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://web.whatsapp.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: FCmMBkUE8N/k0RW1hGSmfA==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

Response Headers:
Status code: 101
Version:HTTP/1.1
Connection: Upgrade
Date: Thu, 16 Nov 2017 22:47:51 GMT
**Server: Kestrel**
Upgrade: websocket
Sec-WebSocket-Accept: enCxmjpawA1hLIBx0G5iVuX1WXA=

Request not using the proxy:

Request Headers:
Host: w6.web.whatsapp.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://web.whatsapp.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: sSnN8MB4fUIVhhYROhqLUw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

Response Header:
Status code: 101
Version:HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: b0HllaSjeZvmTavnZhEwFFgJFg8=

I can only notice the difference in the Kestrel server Header.

@TechnikEmpire  can you take a look ?

**Comment by Hesham-Elbadawi** [comment]
Sorry for posting this here, I think this issue has to be moved to the Citadel Core Project

**Comment by TechnikEmpire** [comment]
Yeah it should be on the core project but that's ok. All the proxy code is in core, this just has diversion for Windows built in.

**Comment by TechnikEmpire** [comment]
Hey @Hesham-Elbadawi Did this by chance happen on Windows 7?

**Comment by Hesham-Elbadawi** [comment]
Hi Jesse,

This was on both win 10 and 8

**Comment by TechnikEmpire** [comment]
Any chance that recent/newer versions have solved this? I made changes to
cookie forwarding and such after this ticket. Microsoft has a lot of issues
with websockets they are addressing in .net core 2.1.0 release but that's
not expected for a couple months.

**Comment by TechnikEmpire** [comment]
Windows 7 simply won't work at all ATM due to previous comment about Microsoft problems.

**Comment by Hesham-Elbadawi** [comment]
I understand the win 7 problem from the issues.
Will test with the latest code and get back to you.
Latest test was done with 1.3.2 i guess

**Comment by TechnikEmpire** [comment]
Closing this because this is an issue with the core engine, referenced here:

https://github.com/TechnikEmpire/CitadelCore/issues/25

That will be patched this afternoon so I'm closing it out here.
