### ISSUE TITLE
Can not block a website using AJAX

### ISSUE THREAD

**Issue by gocict** [TechnikEmpire/CitadelCore.Windows#14]
Hi there!
I used CitadelCore.Windows to block some url and it work very well. But if a website uses AJAX, it seems can't block the url.
I tried to block some url of Youtube but notthing happened.
Sorry for my bad English.
Regard!

**Comment by TechnikEmpire** [comment]
@gocict Every single request should be forced through the proxy and you should be able to see it.

Is the AJAX request going to a different port perhaps? Remember, you can control which ports get intercepted via the firewall callback.

**Comment by TechnikEmpire** [comment]
@gocict If you need to do advanced pattern matched for blocking URLs, look at my project [DistillNET](https://github.com/TechnikEmpire/DistillNET).

It uses the adblock plus filter syntax for URLs and is very fast. It's trivial to plug it in to CitadelCore.

**Comment by gocict** [comment]
@TechnikEmpire I tried to block this url: "https://www.youtube.com/user/MrBean". But when I clicked this channel on the result page of Youtube, it loaded completely normal. Only when I reload the page it will block.

**Comment by gocict** [comment]
Yes, I start the app first, then I open the browser.

**Comment by TechnikEmpire** [comment]
OK can you post a minimal project demonstrating the issue and I'll take a look at it.

**Comment by gocict** [comment]
Oh my god, when I debug, the url is load is "https://www.youtube.com/user/MrBean?pbj=1" not "https://www.youtube.com/user/MrBean" and I used messageInfo.Url.ToString().Equals("https://www.youtube.com/user/MrBean")

**Comment by TechnikEmpire** [comment]
Glad you solved it. Use DistillNet and create a filtering rule and that stuff won't happen. ;)

||YouTube.com^MrBean should work as a rule

**Comment by gocict** [comment]
Thanks, DistillNet is awesome! And how we can set a rule to block xxxfacebook.com or facebookxxx.com or xxxfacebookxxx.com but not block facebook.com

**Comment by TechnikEmpire** [comment]
@gocict The best part is, I don't need to write any documentation. ;)

https://adblockplus.org/filters

https://adblockplus.org/filter-cheatsheet

**Comment by TechnikEmpire** [comment]
There's a lot of different ways you could write that filter. Takes time to understand because the syntax is pretty simple but how you can arrange it gets complex. So for example.

``||xxxfacebook.com``
``||xxx*facebook*xxx.com``
``||xxx$~domain=facebook.com``

etc. Those links will teach you.

**Comment by gocict** [comment]
Yes, thanks so much! But if xxx is a random char, I dont know how to set rule to block it.

**Comment by TechnikEmpire** [comment]
@gocict Just don't put domain anchors. For example, just plain `xxx` as a rule will block any URL that has xxx in it. If you add `match-case` as a rule, then it won't match if it's `XXX` or `xXx` etc.

https://adblockplus.org/en/filters#options
