### ISSUE TITLE
Speed increase by preestablishing MITM-SERVER connection

### ISSUE THREAD

**Issue by hitgubmitt** [TechnikEmpire/CitadelCore.Windows#19]
I noticed that the initial connections to websites are very slow. This is only true for the very first one, all subsequent refreshes gain significant speed boost.  I understand that in order for CitadelCore to work, it need to establish 2 SSL/TCP connections.  One between client and mitm(Kestrel) and one with HttpClient and endpoint server. Moreover, delay for 3 roundtrips needed should be minimal between client and mitm, and very noticable between mitm and server. I expected that the website load(initial request) time should be decreased (or at least stay the same), if the connection between mitm and server is preestablished.

![Untitled-1](https://user-images.githubusercontent.com/60739213/80313573-f4a8f800-87eb-11ea-83af-f8461e0a134c.png)

I tested this idea and implemented a small piece of code in FilterResponseHandlerFactory.cs. On line 94, I added a request to desired website.

            _client = new HttpClient(configuration.CustomProxyHandler, true);
            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://motherfuckingwebsite.com/");
            requestMessage.Headers.Add("Host", "motherfuckingwebsite.com");
            requestMessage.Headers.Add("Connection", "keep-alive");
            requestMessage.Headers.Add("Pragma", "no-cache");
            requestMessage.Headers.Add("Cache-Control", "no-cache");
            requestMessage.Headers.Add("Upgrade-Insecure-Requests", "1");
            requestMessage.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.4044.155 Safari/537.36");
            requestMessage.Headers.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");

            try{
                HttpResponseMessage response = _client.SendAsync(requestMessage).GetAwaiter().GetResult();
                if (response.StatusCode == HttpStatusCode.OK){
                    Console.WriteLine("prefetch done");
                    byte[] buf = response.Content.ReadAsByteArrayAsync().GetAwaiter().GetResult();
                    string content = Encoding.UTF8.GetString(buf);
                }
            }
            catch (Exception e){
                // handle error
            }

I got a 450ms speed increase on first page load compared to no prefetching and 150ms delay, compared to no mitm. I then changed the host and testes for different websites (such as 9gag.com), and got a large deviation from the expected. The speed increase was negligible. 20ms tops, and I am not even sure about that due to network randomness. 

What is your take on this approach? The goal is to optimize first page load. Do you have any implementation recommendations?

**Comment by TechnikEmpire** [comment]
I have no recommendations.
