### ISSUE TITLE
When using CitadelCore.Windows cannot upload image files via facebook, I can't use google translate

### ISSUE THREAD

**Issue by tuntin9x** [TechnikEmpire/CitadelCore.Windows#22]
ajax
https://upload.facebook.com/ajax/mercury/upload.php

**Comment by TechnikEmpire** [comment]
I simply cannot help you with this. This library is a powerful tool. Its like me contacting Dewalt and telling them my house is crooked. If you cannot identify the reason, please close.

**Comment by LinhTQ2810** [comment]
please see the error video for me
https://drive.google.com/file/d/1TBHvSDrYoHlHH16LLPyuO9FHQ1Qp9vnw/view?usp=sharing
thank
